# Generated by Django 3.0.8 on 2020-07-11 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('강릉', 'Gangneung'), ('속초', 'Sokcho'), ('서울', 'Seoul'), ('여수', 'Yeosu'), ('전주', 'Jeonju'), ('제주', 'Jeju'), ('울산', 'Ulsan'), ('남해', 'Namhae'), ('통영', 'Tongyeong'), ('경주', 'Gyeongju')], max_length=10)),
                ('partner', models.CharField(choices=[('1인', 'Single'), ('친구', 'Friends'), ('연인', 'Couple')], max_length=10)),
                ('room_detail', models.CharField(max_length=50)),
                ('room_hash', models.CharField(max_length=50)),
                ('room_img1', models.ImageField(blank=True, default='sample/default1.jpg', upload_to='sample/')),
                ('room_img2', models.ImageField(blank=True, default='sample/default1.jpg', upload_to='sample/')),
                ('room_img3', models.ImageField(blank=True, default='sample/default2.jpg', upload_to='sample/')),
                ('meal_name1', models.CharField(max_length=20)),
                ('meal_detail1', models.CharField(max_length=50)),
                ('meal_hash1', models.CharField(max_length=50)),
                ('meal_img1', models.ImageField(blank=True, default='sample/default1.jpg', upload_to='sample/')),
                ('meal_name2', models.CharField(max_length=20)),
                ('meal_detail2', models.CharField(max_length=50)),
                ('meal_hash2', models.CharField(max_length=50)),
                ('meal_img2', models.ImageField(blank=True, default='sample/default1.jpg', upload_to='sample/')),
                ('meal_name3', models.CharField(max_length=20)),
                ('meal_detail3', models.CharField(max_length=50)),
                ('meal_hash3', models.CharField(max_length=50)),
                ('meal_img3', models.ImageField(blank=True, default='sample/default2.jpg', upload_to='sample/')),
                ('meal_name4', models.CharField(max_length=20)),
                ('meal_detail4', models.CharField(max_length=50)),
                ('meal_hash4', models.CharField(max_length=50)),
                ('meal_img4', models.ImageField(blank=True, default='sample/default1.jpg', upload_to='sample/')),
                ('meal_name5', models.CharField(max_length=20)),
                ('meal_detail5', models.CharField(max_length=50)),
                ('meal_hash5', models.CharField(max_length=50)),
                ('meal_img5', models.ImageField(blank=True, default='sample/default1.jpg', upload_to='sample/')),
                ('meal_name6', models.CharField(max_length=20)),
                ('meal_detail6', models.CharField(max_length=50)),
                ('meal_hash6', models.CharField(max_length=50)),
                ('meal_img6', models.ImageField(blank=True, default='sample/default2.jpg', upload_to='sample/')),
                ('act_name1', models.CharField(blank=True, max_length=20)),
                ('act_detail1', models.CharField(blank=True, max_length=50)),
                ('act_hash1', models.CharField(blank=True, max_length=50)),
                ('act_img1', models.ImageField(blank=True, default='sample/default1.jpg', upload_to='sample/')),
                ('act_name2', models.CharField(blank=True, max_length=20)),
                ('act_detail2', models.CharField(blank=True, max_length=50)),
                ('act_hash2', models.CharField(blank=True, max_length=50)),
                ('act_img2', models.ImageField(blank=True, default='sample/default1.jpg', upload_to='sample/')),
                ('act_name3', models.CharField(blank=True, max_length=20)),
                ('act_detail3', models.CharField(blank=True, max_length=50)),
                ('act_hash3', models.CharField(blank=True, max_length=50)),
                ('act_img3', models.ImageField(blank=True, default='sample/default2.jpg', upload_to='sample/')),
                ('result_img', models.ImageField(blank=True, default='sample/default1.jpg', upload_to='sample/')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.BigIntegerField(null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_price', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='api.CoursePrice')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('강릉', 'Gangneung'), ('속초', 'Sokcho'), ('서울', 'Seoul'), ('여수', 'Yeosu'), ('전주', 'Jeonju'), ('제주', 'Jeju'), ('울산', 'Ulsan'), ('남해', 'Namhae'), ('통영', 'Tongyeong'), ('경주', 'Gyeongju')], max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('1인', 'Single'), ('친구', 'Friends'), ('연인', 'Couple')], max_length=20)),
                ('contact', models.BigIntegerField(null=True)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('강릉', 'Gangneung'), ('속초', 'Sokcho'), ('서울', 'Seoul'), ('여수', 'Yeosu'), ('전주', 'Jeonju'), ('제주', 'Jeju'), ('울산', 'Ulsan'), ('남해', 'Namhae'), ('통영', 'Tongyeong'), ('경주', 'Gyeongju')], max_length=20)),
                ('sample_img', models.ImageField(blank=True, default='sample/default1.jpg', upload_to='sample/')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('succeed_at', models.DateTimeField(auto_now_add=True)),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Payment')),
                ('res_course', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='room_price',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RoomPrice'),
        ),
        migrations.AddField(
            model_name='course',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Rooms'),
        ),
    ]
