# Generated by Django 3.0.8 on 2021-12-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='act_img1',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='act_img2',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='act_img3',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='city',
            field=models.CharField(choices=[('강릉', 'Gangneung'), ('속초', 'Sokcho'), ('서울', 'Seoul'), ('여수', 'Yeosu'), ('전주', 'Jeonju'), ('제주', 'Jeju'), ('울릉도', 'Ulleungdo'), ('남해', 'Namhae'), ('통영', 'Tongyeong'), ('냠원', 'Namwon')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='meal_img1',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meal_img2',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meal_img3',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meal_img4',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meal_img5',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meal_img6',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='result_img',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='room_img1',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='room_img2',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='room_img3',
            field=models.ImageField(blank=True, default='sample', upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='location',
            field=models.CharField(choices=[('강릉', 'Gangneung'), ('속초', 'Sokcho'), ('서울', 'Seoul'), ('여수', 'Yeosu'), ('전주', 'Jeonju'), ('제주', 'Jeju'), ('울릉도', 'Ulleungdo'), ('남해', 'Namhae'), ('통영', 'Tongyeong'), ('냠원', 'Namwon')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='city',
            field=models.CharField(choices=[('강릉', 'Gangneung'), ('속초', 'Sokcho'), ('서울', 'Seoul'), ('여수', 'Yeosu'), ('전주', 'Jeonju'), ('제주', 'Jeju'), ('울릉도', 'Ulleungdo'), ('남해', 'Namhae'), ('통영', 'Tongyeong'), ('냠원', 'Namwon')], max_length=20),
        ),
    ]
