# Generated by Django 3.0.8 on 2021-12-30 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211223_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='activity_price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='room_price',
        ),
        migrations.RemoveField(
            model_name='roomprice',
            name='room',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='succeed_at',
            new_name='booked_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pay',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.ForeignKey(db_column='price', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course_payment', to='api.Course'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CoursePrice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='RoomPrice',
        ),
    ]
